# Generated by Django 5.2 on 2025-07-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_label_schema_project_label_type_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='label_type',
            field=models.CharField(choices=[('SI', 'Single-Label (Radio)'), ('MU', 'Multi-Label (Checkbox)')], max_length=2),
        ),
    ]
