# Generated by Django 5.2.3 on 2025-06-27 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_label_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='label',
            unique_together={('project', 'value')},
        ),
    ]
