# Generated by Django 5.2 on 2025-07-08 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_label_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='label',
            options={'ordering': ['label']},
        ),
        migrations.AlterUniqueTogether(
            name='label',
            unique_together={('project', 'value')},
        ),
    ]
