# Generated by Django 5.2.3 on 2025-07-01 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_label_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(help_text='Eindeutige Kennung aus der CSV-Datei', max_length=255, unique=True)),
            ],
        ),
    ]
