# Generated by Django 5.2.3 on 2025-07-01 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_dataitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dataitem',
        ),
    ]
