# Generated by Django 5.2 on 2025-07-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataitem', '0003_remove_dataitem_uploaded_file_dataitem_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100, unique=True)),
                ('text', models.TextField()),
            ],
        ),
    ]
