# Generated by Django 5.2 on 2025-07-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataitem', '0003_remove_dataitem_uploaded_file_dataitem_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataitem',
            name='external_id',
            field=models.CharField(default=-1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
