# Generated by Django 5.2.3 on 2025-07-01 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataitem', '0003_remove_dataitem_uploaded_file_dataitem_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataitem',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
