# Generated by Django 5.2.3 on 2025-07-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataitem', '0004_dataitem_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataitem',
            name='external_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
