# Generated by Django 5.2 on 2025-07-08 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataitem', '0004_dataitem_external_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='dataitem',
            name='name',
        ),
    ]
