# Generated by Django 5.2 on 2025-07-09 13:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataitem', '0004_dataentry'),
        ('projects', '0005_alter_label_options_alter_label_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataentry',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataitem',
            name='external_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
