# Generated by Django 5.2 on 2025-07-10 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataitem', '0005_dataentry_project_dataitem_external_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataEntry',
        ),
    ]
