# Generated by Django 5.2 on 2025-07-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataitem', '0006_delete_dataentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataitem',
            name='external_id',
            field=models.CharField(max_length=100),
        ),
    ]
