# Generated by Django 5.2.3 on 2025-07-07 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataitem', '0006_alter_dataitem_project_databatch'),
        ('projects', '0007_delete_dataitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataitem',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dataitems', to='dataitem.databatch'),
        ),
        migrations.AlterField(
            model_name='dataitem',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='dataitem',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AlterField(
            model_name='dataitem',
            name='text',
            field=models.TextField(),
        ),
    ]
