# Generated by Django 5.2.3 on 2025-07-07 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataitem', '0007_dataitem_batch_alter_dataitem_name_and_more'),
        ('projects', '0007_delete_dataitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataitem',
            name='external_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='dataitem',
            unique_together={('project', 'external_id')},
        ),
    ]
