# Generated by Django 5.2.3 on 2025-07-09 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataitem', '0008_alter_dataitem_external_id_and_more'),
        ('projects', '0007_delete_dataitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('annotator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to=settings.AUTH_USER_MODEL)),
                ('dataitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='dataitem.dataitem')),
            ],
        ),
        migrations.CreateModel(
            name='AnnotationLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='dataitem.annotation')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotation_labels', to='projects.label')),
            ],
        ),
    ]
