# Generated by Django 5.2 on 2025-07-21 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0006_alter_annotation_annotated_by_and_more'),
        ('projects', '0005_alter_label_options_alter_label_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
            preserve_default=False,
        ),
    ]
