# Generated by Django 5.2 on 2025-07-21 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0007_annotation_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='project',
        ),
    ]
